Fix link step when specifying CLANG_CXX_LIBRARY
When using C++ library, pass the -stdlib flag to the linker so that the
correct library is linked against the binary.

The test allocate a string on the stack in order to check that the correct
library is linked. This is sufficient since libc++ and libstdc++ have an
incompatible ABI and linking fails if compilation and link does not use the
same value for -stdlib flag.

For example, if using -stdlib=libc++ when compiling and -stdlib=libstdc++
when linking the test program result in the following compilation error:

FAILED: /usr/bin/clang++ -mmacosx-version-min=10.7 -arch x86_64 -L. -o libc++ obj/libc++.libc++.o
Undefined symbols for architecture x86_64:
  "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::~basic_string()", referenced from:
      _main in libc++.libc++.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

BUG=gyp:425
R=thakis@chromium.org

Review URL: https://codereview.chromium.org/284223008